from .newapi_banana2_node import (
    NODE_CLASS_MAPPINGS as BANANA2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BANANA2_NODE_DISPLAY_NAME_MAPPINGS,
)
from .sora2_niuniu_node import (
    NODE_CLASS_MAPPINGS as SORA2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SORA2_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(BANANA2_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SORA2_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(BANANA2_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SORA2_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
